server:
  port: ${PORT:8084}

spring:
  application:
    name: cms
  jackson:
    serialization:
      fail-on-self-references: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER:http://localhost:9090/auth/realms/platform}

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug
    ba.majid.quiz: debug
