server:
  port: ${PORT:8084}

spring:
  application:
    name: cms
  jackson:
    serialization:
      fail-on-self-references: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER:http://localhost:9090/auth/realms/platform}

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    oauth:
      clientId: swagger-ui-quiz
      clientSecret:
  oAuthFlow:
    authorizationUrl: http://localhost:9090/auth/realms/platform/protocol/openid-connect/auth
    tokenUrl: http://localhost:9090/auth/realms/platform/protocol/openid-connect/token

logging:
  level:
    root: info
    org.springframework: debug
    org.springframework.security: debug
    ba.majid.quiz: debug

