server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER:http://localhost:9090/auth/realms/platform}

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: simple-greetings
          predicates:
          - Path=/resources/greetings
          filters:
          - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          - name: CircuitBreaker
            args:
              name: fallbackCommand
              fallbackUri: forward:/fallback/message
          uri: lb://greetings-service

        - id: echo-message
          predicates:
            - Path=/resources/echo
          filters:
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
          uri: lb://greetings-service
        - id: quiz
          predicates:
            - Path=/quiz/**
          filters:
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
          uri: lb://cms

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, gateway, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: error
    org.springframework.web: debug
    dev.demo: debug
