server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: message-source
          uri: lb://greetings-service
          predicates:
          - Path=/greetings
          filters:
          - name: CircuitBreaker
            args:
              name: fallbackCommand
              fallbackUri: forward:/fallback/message


eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, gateway, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: error
    org.springframework: info
    dev.demo: debug
