
server:
  port: ${PORT:8090}
spring:
  application:
    name: caller-service

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
